name: ArzioLib
main: com.arzio.arziolib.ArzioLib
version: {PROJECT_VERSION}
author: Arzio
load: STARTUP
depend: [ProtocolLib, WorldGuard, WGCustomFlags]
softdepend: [PlotMe, AuthMe, Essentials]
description: Library of tools for Crafting Dead servers.
commands:
    particle:
        description: Disables/Enables bullet particles for you
        usage: /particle
        aliases: [ particles, particula, particulas ]
    test:
        description: Runs a test case
        usage: /test
        aliases: [ te ]
    clothes:
        description: Disables/Enables other players clothes to increase your FPS
        usage: /clothes
        aliases: [ cloth, clothing, roupa, roupas ]
    arziolib:
        description: Main command for the plugin
        usage: /arziolib to see the comands
        aliases: [ arzio ]
    thirst:
        description: Heals your thirst
        usage: /thirst
        aliases: [ sede ]
    thirstall:
        description: Heals thirst for all players
        usage: /thirstall
        aliases: [ sedeall ]
    ping:
        description: Command to check your ping
        usage: /ping
    nodelay:
        description: Disables/Enables TCP NODELAY feature for you
        usage: /nodelay